# ~/paradox/infra/compose/docker-compose.yml

services:
  postgres_keycloak:
    image: postgres:16
    container_name: ppx-kc-postgres
    environment:
      POSTGRES_DB: ${KC_DB_NAME:-keycloak}
      POSTGRES_USER: ${KC_DB_USER:-kc}
      POSTGRES_PASSWORD: ${KC_DB_PASS:-kcpass}
      TZ: ${TZ:-Europe/Berlin}
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER:-kc} -d ${KC_DB_NAME:-keycloak}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [core]

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: ppx-keycloak
    command:
      - start-dev
      - --http-relative-path=/auth
      - --hostname-strict=false
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASS:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/${KC_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KC_DB_USER:-kc}
      KC_DB_PASSWORD: ${KC_DB_PASS:-kcpass}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      TZ: ${TZ:-Europe/Berlin}
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    expose: ["8080","9000"]   # Hinweis: kein Healthcheck hier
    restart: unless-stopped
    networks: [core]

  redis:
    image: redis:7
    container_name: ppx-redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks: [core]

  bff:
    build:
      context: ../../apps/bff
      dockerfile: Dockerfile
    image: compose-bff
    container_name: compose-bff-1
    env_file:
      - ../../apps/bff/.env
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
      COOKIE_SECURE: "${COOKIE_SECURE:-false}"
      COOKIE_SAMESITE: "${COOKIE_SAMESITE:-Lax}"
      SESSION_TTL_SECONDS: "${SESSION_TTL_SECONDS:-604800}"
      TZ: ${TZ:-Europe/Berlin}
    depends_on:
      keycloak:
        condition: service_started     # <— geändert
      redis:
        condition: service_healthy
    expose: ["3000"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/bff/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped
    networks: [core, edge]

  nginx:
    image: nginx:1.27
    container_name: ppx-nginx
    volumes:
      - ../nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/keycloak-ssl.conf:/etc/nginx/conf.d/keycloak-ssl.conf:ro
      - ../nginx/tls:/etc/nginx/tls:ro
    ports:
      - "80:80"
      - "8443:8443"
    depends_on:
      keycloak:
        condition: service_started     # <— geändert
      bff:
        condition: service_healthy
    restart: unless-stopped
    networks: [edge, core]

volumes:
  kc_pgdata:
  redisdata:

networks:
  core:
  edge:
